version: '3.8'

services:
  php-web:
    build:
      context: .
      dockerfile: docker/php-web/Dockerfile
    volumes:
      - .:/var/www
    environment:
      APP_ENV: development
      # TODO: User ändern
      MYSQL_HOSTNAME: mariadb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: news_articles
      MYSQL_PORT: 3306

  nginx-backend:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www

  mariadb:
    image: mariadb:10.6-focal
    ports:
      - "13306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
      - "./data/sql/:/docker-entrypoint-initdb.d/:ro"
    environment:
      MARIADB_ROOT_PASSWORD: "1234"
      MARIADB_DATABASE: news_articles

  pma:
    image: phpmyadmin:5.1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

volumes:
  db-data:
