version: '3.8'

services:
  php-web:
    build:
      context: .
      dockerfile: docker/php-web/Dockerfile
# Zur lokalen Entwicklung können die auskommentierten Volumes einkommentiert werden.
#    volumes:
#      - .:/var/www/html
    environment:
      APP_ENV: development
      MYSQL_HOSTNAME: mariadb
      MYSQL_USERNAME: testing
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: news_articles
      MYSQL_PORT: 3306

  nginx-backend:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
#    volumes:
#      - .:/var/www/html

  mariadb:
    image: mariadb:10.6-focal
    ports:
      - "13306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
      - "./data/sql/:/docker-entrypoint-initdb.d/:ro"
    environment:
      # Die Zugangsdaten sind nur für eine Entwicklungsumgebung gedacht. Reale Zugangsdaten sollten weder öffentlich noch so unsicher sein
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: news_articles
      MARIADB_USER: testing
      MARIADB_PASSWORD: 1234

  pma:
    image: phpmyadmin:5.1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

volumes:
  db-data:
